// TODO use this file

const cryptoAssetSymbols = {
  BTC: "BTC",
  ETH: "ETH",
  LTC: "LTC",
};

const coinNames = {
  ADA: "Cardano",
  ADX: "AdEx",
  AE: "Aeternity",
  AGI: "SingularityNET",
  AION: "Aion",
  ALGO: "Algorand",
  AMB: "Ambrosus",
  ANKR: "Ankr",
  ANT: "Aragon",
  APPC: "AppCoins",
  ARDR: "Ardor",
  ARK: "Ark",
  ARPA: "ARPA Chain",
  AST: "AirSwap",
  ATOM: "Cosmos",
  AUD: null,
  AVA: "Travala.com",
  BAL: "Balancer",
  BAND: "Band Protocol",
  BAT: "Basic Attention Token",
  BCD: "Bitcoin Diamond",
  BCH: "Bitcoin Cash",
  BCPT: "Blockmason Credit Protocol",
  BEAM: "BEAM",
  BGBP: "Binance GBP Stable Coin",
  BLZ: "Bluzelle",
  BNB: "Binance Coin",
  BNT: "Bancor Network Token",
  BQX: null,
  BRD: "Bread",
  BTC: "Bitcoin",
  BTG: "Bitcoin Gold",
  BTS: null,
  BTT: null,
  BUSD: "Binance USD",
  BZRX: "bZx Protocol",
  CDT: "Blox",
  CELR: "Celer Network",
  CHR: "Chromia",
  CHZ: "Chiliz",
  CMT: null,
  CND: null,
  COCOS: "COCOS BCX",
  COMP: null,
  COS: "Contentos",
  COTI: "COTI",
  CRV: "Curve DAO Token",
  CTSI: "Cartesi",
  CTXC: "Cortex",
  CVC: "Civic",
  DASH: "Dash",
  DATA: "Streamr DATAcoin",
  DCR: "Decred",
  DENT: "Dent",
  DGB: "DigiByte",
  DIA: "DIA",
  DLT: null,
  DNT: "district0x",
  DOCK: "Dock",
  DOGE: "Dogecoin",
  DOT: "Polkadot",
  DREP: "Drep",
  DUSK: "DUSK Network",
  ELF: "aelf",
  ENG: "Enigma",
  ENJ: "Enjin Coin",
  EOS: "EOS",
  ETC: "Ethereum Classic",
  ETH: "Ethereum",
  EUR: null,
  EVX: "Everex",
  FET: null,
  FIO: "FIO Protocol",
  FTM: "Fantom",
  FTT: null,
  FUN: "FunFair",
  GAS: "Gas",
  GBP: null,
  GNT: "Golem",
  GO: null,
  GRS: "Groestlcoin",
  GTO: "Gifto",
  GVT: "Genesis Vision",
  GXS: null,
  HBAR: "Hedera Hashgraph",
  HC: "HyperCash",
  HIVE: "Hive",
  HOT: null,
  ICX: "ICON",
  IDEX: "IDEX",
  INS: "Insolar (Old)",
  IOST: "IOST",
  IOTA: null,
  IOTX: "IoTeX",
  IQ: null,
  IRIS: "IRISnet",
  JST: "JUST",
  KAVA: "Kava",
  KEY: null,
  KMD: "Komodo",
  KNC: "Kyber Network",
  KSM: "Kusama",
  LEND: "Aave",
  LINK: "ChainLink",
  LOOM: "Loom Network",
  LRC: "Loopring",
  LSK: "Lisk",
  LTC: "Litecoin",
  LTO: "LTO Network",
  LUNA: "Terra",
  MANA: "Decentraland",
  MATIC: "Matic Network",
  MBL: "MovieBloc",
  MCO: "MCO",
  MDA: "Moeda Loyalty Points",
  MDT: "Measurable Data Token",
  MFT: "Mainframe",
  MITH: "Mithril",
  MKR: "Maker",
  MTH: "Monetha",
  MTL: "Metal",
  NANO: "Nano",
  NAS: "Nebulas",
  NAV: "NavCoin",
  NCASH: "Nucleus Vision",
  NEBL: "Neblio",
  NEO: "NEO",
  NKN: "NKN",
  NMR: "Numeraire",
  NPXS: "Pundi X",
  NULS: "Nuls",
  NXS: "Nexus",
  OAX: "OAX",
  OCEAN: "Ocean Protocol",
  OGN: "Origin Protocol",
  OMG: "OMG Network",
  ONE: null,
  ONG: null,
  ONT: "Ontology",
  OST: "OST",
  PAX: null,
  PAXG: "PAX Gold",
  PERL: "Perlin",
  PHB: null,
  PIVX: "PIVX",
  PNT: null,
  POA: "POA Network",
  POE: "Po.et",
  POLY: "Polymath Network",
  POWR: "Power Ledger",
  PPT: "Populous",
  QKC: "QuarkChain",
  QLC: "QLC Chain",
  QSP: "Quantstamp",
  QTUM: "Qtum",
  RCN: "Ripio Credit Network",
  RDN: "Raiden Network Token",
  REN: "REN",
  REP: "Augur",
  REQ: "Request",
  RLC: "iExec RLC",
  RSR: "Reserve Rights Token",
  RUNE: "Thorchain",
  RVN: "Ravencoin",
  SAND: null,
  SC: "Siacoin",
  SKY: "Skycoin",
  SNGLS: "SingularDTV",
  SNM: "SONM",
  SNT: "Status",
  SNX: "Synthetix Network Token",
  SOL: "Solana",
  SRM: "Serum",
  STEEM: "Steem",
  STMX: "StormX",
  STORJ: "Storj",
  STPT: "STP Network",
  STRAT: "Stratis",
  STX: null,
  SUSHI: "Sushi",
  SXP: "Swipe",
  SYS: "Syscoin",
  TCT: null,
  TFUEL: "Theta Fuel",
  THETA: "Theta Network",
  TNB: null,
  TNT: null,
  TOMO: "TomoChain",
  TRB: "Tellor",
  TROY: "Troy",
  TRX: "TRON",
  TUSD: "TrueUSD",
  USDC: "USD Coin",
  USDT: "Tether",
  VET: "VeChain",
  VIA: "Viacoin",
  VIB: "Viberate",
  VIBE: "VIBE",
  VITE: "Vite",
  VTHO: "VeThor Token",
  WABI: "Tael",
  WAN: "Wanchain",
  WAVES: "Waves",
  WBTC: "Wrapped Bitcoin",
  WIN: null,
  WNXM: "Wrapped NXM",
  WPR: "WePower",
  WRX: "WazirX",
  WTC: "Waltonchain",
  XEM: "NEM",
  XLM: "Stellar",
  XMR: "Monero",
  XRP: "XRP",
  XTZ: "Tezos",
  XVG: "Verge",
  XZC: "Zcoin",
  YFI: "yearn.finance",
  YFII: "DFI.money",
  YOYO: null,
  ZEC: "Zcash",
  ZEN: "Horizen",
  ZIL: "Zilliqa",
  ZRX: "0x",
};

// const fiatAssetSymbols = {
//   USD:'USD' ...
// };

export { cryptoAssetSymbols };
